/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LiveMonitorRouteImport } from './routes/live-monitor'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SensorAnalyticsRouteImport } from './routes/sensor-analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMonitorRoute = LiveMonitorRouteImport.update({
  id: '/live-monitor',
  path: '/live-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorAnalyticsRoute = SensorAnalyticsRouteImport.update({
  id: '/sensor-analytics',
  path: '/sensor-analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/live-monitor': typeof LiveMonitorRoute
  '/reports': typeof ReportsRoute
  '/sensor-analytics': typeof SensorAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/live-monitor': typeof LiveMonitorRoute
  '/reports': typeof ReportsRoute
  '/sensor-analytics': typeof SensorAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/live-monitor': typeof LiveMonitorRoute
  '/reports': typeof ReportsRoute
  '/sensor-analytics': typeof SensorAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/history' | '/live-monitor' | '/reports' | '/sensor-analytics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/live-monitor' | '/reports' | '/sensor-analytics'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/live-monitor'
    | '/reports'
    | '/sensor-analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  LiveMonitorRoute: typeof LiveMonitorRoute
  ReportsRoute: typeof ReportsRoute
  SensorAnalyticsRoute: typeof SensorAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-monitor': {
      id: '/live-monitor'
      path: '/live-monitor'
      fullPath: '/live-monitor'
      preLoaderRoute: typeof LiveMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensor-analytics': {
      id: '/sensor-analytics'
      path: '/sensor-analytics'
      fullPath: '/sensor-analytics'
      preLoaderRoute: typeof SensorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  LiveMonitorRoute: LiveMonitorRoute,
  ReportsRoute: ReportsRoute,
  SensorAnalyticsRoute: SensorAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
