/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveMonitorRouteImport } from './routes/live-monitor'
import { Route as SensorAnalyticsRouteImport } from './routes/sensor-analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMonitorRoute = LiveMonitorRouteImport.update({
  id: '/live-monitor',
  path: '/live-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorAnalyticsRoute = SensorAnalyticsRouteImport.update({
  id: '/sensor-analytics',
  path: '/sensor-analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live-monitor': typeof LiveMonitorRoute
  '/sensor-analytics': typeof SensorAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live-monitor': typeof LiveMonitorRoute
  '/sensor-analytics': typeof SensorAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live-monitor': typeof LiveMonitorRoute
  '/sensor-analytics': typeof SensorAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/live-monitor' | '/sensor-analytics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/live-monitor' | '/sensor-analytics'
  id: '__root__' | '/' | '/live-monitor' | '/sensor-analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveMonitorRoute: typeof LiveMonitorRoute
  SensorAnalyticsRoute: typeof SensorAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-monitor': {
      id: '/live-monitor'
      path: '/live-monitor'
      fullPath: '/live-monitor'
      preLoaderRoute: typeof LiveMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensor-analytics': {
      id: '/sensor-analytics'
      path: '/sensor-analytics'
      fullPath: '/sensor-analytics'
      preLoaderRoute: typeof SensorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveMonitorRoute: LiveMonitorRoute,
  SensorAnalyticsRoute: SensorAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
